services:
  - type: web
    name: ThuThapCCCD
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip==25.3
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16